---
#
# Ansible managed
#
repository:
  description: Install and configure ansible on your system.
  homepage: https://robertdebock.nl/
  topics: ansible, system, development, ansible, molecule, tox, playbook
