---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="latest"
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="debian" tag="latest"
    - image="debian" tag="unstable"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "DIjA6Mnh2fpuFs+CYMtn1DX0o1DWqiz5Jz4v39fjeF+CJsG0vMFpmHunRwqftVnGUpsJKrjH9zxZXL5EkAtMif4ROC885h+uc0YgWoNl1cnlZUfljD3+34+EjutW6W/wcijxqy7v0LqracBScDSErUzBnZO6fBUFdf/6KIsyWxOrKTEH4cjt5SocEDUYUy3CQZDIU4pXdfoliWPnb0MDjiRN2NV4paB5R2CQ0NawlUV8gwrA5hKOUGD6ca0LNOF/tnkOcF8qJKox4AyYMXvAJdieFO/aWQG5tZg2y5+yDXqQPyjuTTX7XiqNUpdyeP0mwR27eAO/R7LBiRMqiYPFkT2ttSN4ufKWToGX51lAZXZWmKfy8lKcFxszVwthJj4PQvjLcY/xbk9Ze1o+yz/1H4eBdmXEVD+H9SX3j2wToerbhktHcv+Uf62xrug8UglxQsSJFHRWaSkiC6ZWw5Awce+9LxHi8VK9ubnFKD7wK5iY+Gved4A7HvwSUQJQfCeNnyvmsLwacnr1DGTUzm0/LkbtkAQMh4h5ouDN5b1vwalcADHFZmmqtDeocZQL6m8E42Fvkpkllfo0tJV67aN3Of6fq/e/I5Ac+dOqJ0MQkclnGG4+HvSa12MAoTKhrgFIBkpJI/083i6eoRsmIT2gtHwGzclVNKJmRERcrVLLa1s="
  email: false
