---
# tasks file for ansible
- name: test veriables and environment
  assert:
    that:
      - ansible_package_state is defined
      - ansible_package_state == "present" or
        ansible_package_state == "latest" or
        ansible_package_state == "absent"

- name: install ansible
  package:
    name: "{{ ansible_packages }}"
    state: "{{ ansible_package_state }}"
  register: ansible_install_ansible
  until: ansible_install_ansible is succeeded
  retries: 3

- name: ensure the ansible directory exists
  file:
    path: /etc/ansible
    state: directory

- name: configure ansible
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    validate: ANSIBLE_CONFIG=%s ansible --module-name ping --inventory localhost, --check
