---
# tasks file for ansible
- name: test veriables and environment
  assert:
    that:
      - ansible_package_state is defined
      - ansible_package_state == "present" or
        ansible_package_state == "latest" or
        ansible_package_state == "absent"

- name: install ansible
  package:
    name: "{{ ansible_packages }}"
    state: "{{ ansible_package_state }}"
  register: ansible_install_ansible
  until: ansible_install_ansible is succeeded
  retries: 3
