---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: ansible-debian-latest
    image: debian:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-latest
